language: node_js
node_js:
- 10.15.1
addons:
  ssh_known_hosts: 68.183.160.56
before_install:
- openssl aes-256-cbc -K $encrypted_cda9b02fa8ba_key -iv $encrypted_cda9b02fa8ba_iv
  -in deployuser.enc -out deployuser -d
- chmod 700 deployuser
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: master
env:
  global:
  - KEY_PATH="./deployuser"
  - REMOTE_REPO="deploy@68.183.160.56:/var/www/console-typer"
  - GIT_USERNAME="Travis CI"
  - GIT_EMAIL="travis@danielzamorano.pro"
  - GIT_COMMIT_MESSAGE="New Deploy"
  - DEPLOY_FOLDER="./*"
